name: Build Application
description: This action builds the main application for the project.
inputs:
  os:
    description: "The operating system to build for."
    required: true
  # arch:
  #   description: "The architecture to build for."
  #   required: true
  shell:
    description: "The shell to use for running commands."
    required: true
    default: "bash"

runs:
  using: composite
  steps:
    - name: Build jp-learning-tools
      shell: ${{ inputs.shell }}
      run: |
        nx run jp-learning-tools:build:${{ inputs.os }}
