// Autogenerated from Pigeon (v26.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class GetDecks (
  val decks: Map<Long, String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GetDecks {
      val decks = pigeonVar_list[0] as Map<Long, String>
      return GetDecks(decks)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      decks,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GetDecks
    return MessagesPigeonUtils.deepEquals(this.decks, other.decks)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.decks)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GetModels (
  val models: Map<Long, String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GetModels {
      val models = pigeonVar_list[0] as Map<Long, String>
      return GetModels(models)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      models,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GetModels
    return MessagesPigeonUtils.deepEquals(this.models, other.models)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.models)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ModelInfo (
  val modelId: Long,
  val modelName: String,
  val noteCount: Long,
  val fields: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ModelInfo {
      val modelId = pigeonVar_list[0] as Long
      val modelName = pigeonVar_list[1] as String
      val noteCount = pigeonVar_list[2] as Long
      val fields = pigeonVar_list[3] as List<String>
      return ModelInfo(modelId, modelName, noteCount, fields)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      modelId,
      modelName,
      noteCount,
      fields,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ModelInfo
    return MessagesPigeonUtils.deepEquals(this.modelId, other.modelId) && MessagesPigeonUtils.deepEquals(this.modelName, other.modelName) && MessagesPigeonUtils.deepEquals(this.noteCount, other.noteCount) && MessagesPigeonUtils.deepEquals(this.fields, other.fields)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.modelId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.modelName)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.noteCount)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.fields)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GetModelsWithInfo (
  val models: List<ModelInfo>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GetModelsWithInfo {
      val models = pigeonVar_list[0] as List<ModelInfo>
      return GetModelsWithInfo(models)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      models,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GetModelsWithInfo
    return MessagesPigeonUtils.deepEquals(this.models, other.models)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.models)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GetModelFields (
  val fields: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GetModelFields {
      val fields = pigeonVar_list[0] as List<String>
      return GetModelFields(fields)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      fields,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GetModelFields
    return MessagesPigeonUtils.deepEquals(this.fields, other.fields)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.fields)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NoteWithFields (
  val noteId: Long,
  val modelId: Long,
  val kanji: String,
  val tags: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NoteWithFields {
      val noteId = pigeonVar_list[0] as Long
      val modelId = pigeonVar_list[1] as Long
      val kanji = pigeonVar_list[2] as String
      val tags = pigeonVar_list[3] as List<String>
      return NoteWithFields(noteId, modelId, kanji, tags)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      noteId,
      modelId,
      kanji,
      tags,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NoteWithFields
    return MessagesPigeonUtils.deepEquals(this.noteId, other.noteId) && MessagesPigeonUtils.deepEquals(this.modelId, other.modelId) && MessagesPigeonUtils.deepEquals(this.kanji, other.kanji) && MessagesPigeonUtils.deepEquals(this.tags, other.tags)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.noteId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.modelId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.kanji)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.tags)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GetNotesWithFieldsForModel (
  val notes: List<NoteWithFields>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GetNotesWithFieldsForModel {
      val notes = pigeonVar_list[0] as List<NoteWithFields>
      return GetNotesWithFieldsForModel(notes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      notes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GetNotesWithFieldsForModel
    return MessagesPigeonUtils.deepEquals(this.notes, other.notes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.notes)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CardInfo (
  val noteId: Long,
  val cardOrd: Long,
  val deckId: Long,
  val question: String,
  val answer: String,
  val modelId: Long,
  val kanji: String,
  val tags: List<String>,
  val reps: Long,
  val lapses: Long,
  val type: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CardInfo {
      val noteId = pigeonVar_list[0] as Long
      val cardOrd = pigeonVar_list[1] as Long
      val deckId = pigeonVar_list[2] as Long
      val question = pigeonVar_list[3] as String
      val answer = pigeonVar_list[4] as String
      val modelId = pigeonVar_list[5] as Long
      val kanji = pigeonVar_list[6] as String
      val tags = pigeonVar_list[7] as List<String>
      val reps = pigeonVar_list[8] as Long
      val lapses = pigeonVar_list[9] as Long
      val type = pigeonVar_list[10] as Long
      return CardInfo(noteId, cardOrd, deckId, question, answer, modelId, kanji, tags, reps, lapses, type)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      noteId,
      cardOrd,
      deckId,
      question,
      answer,
      modelId,
      kanji,
      tags,
      reps,
      lapses,
      type,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CardInfo
    return MessagesPigeonUtils.deepEquals(this.noteId, other.noteId) && MessagesPigeonUtils.deepEquals(this.cardOrd, other.cardOrd) && MessagesPigeonUtils.deepEquals(this.deckId, other.deckId) && MessagesPigeonUtils.deepEquals(this.question, other.question) && MessagesPigeonUtils.deepEquals(this.answer, other.answer) && MessagesPigeonUtils.deepEquals(this.modelId, other.modelId) && MessagesPigeonUtils.deepEquals(this.kanji, other.kanji) && MessagesPigeonUtils.deepEquals(this.tags, other.tags) && MessagesPigeonUtils.deepEquals(this.reps, other.reps) && MessagesPigeonUtils.deepEquals(this.lapses, other.lapses) && MessagesPigeonUtils.deepEquals(this.type, other.type)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.noteId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.cardOrd)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.deckId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.question)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.answer)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.modelId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.kanji)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.tags)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.reps)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.lapses)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GetCardsForModel (
  val cards: List<CardInfo>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GetCardsForModel {
      val cards = pigeonVar_list[0] as List<CardInfo>
      return GetCardsForModel(cards)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      cards,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GetCardsForModel
    return MessagesPigeonUtils.deepEquals(this.cards, other.cards)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.cards)
    return result
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GetDecks.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GetModels.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ModelInfo.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GetModelsWithInfo.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GetModelFields.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NoteWithFields.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GetNotesWithFieldsForModel.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CardInfo.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GetCardsForModel.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is GetDecks -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is GetModels -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is ModelInfo -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is GetModelsWithInfo -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is GetModelFields -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is NoteWithFields -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is GetNotesWithFieldsForModel -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is CardInfo -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is GetCardsForModel -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NativeApi {
  fun getDecks(): GetDecks
  fun getModels(): GetModels
  fun getModelsWithInfo(): GetModelsWithInfo
  fun getModelFields(modelId: Long): GetModelFields
  fun getNotesWithFieldsForModel(modelId: Long, fieldName: String): GetNotesWithFieldsForModel
  fun getCardsForModel(modelId: Long, fieldName: String, offset: Long, limit: Long): GetCardsForModel

  companion object {
    /** The codec used by NativeApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `NativeApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.kanji_scanner.NativeApi.getDecks$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getDecks())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.kanji_scanner.NativeApi.getModels$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getModels())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.kanji_scanner.NativeApi.getModelsWithInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getModelsWithInfo())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.kanji_scanner.NativeApi.getModelFields$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modelIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.getModelFields(modelIdArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.kanji_scanner.NativeApi.getNotesWithFieldsForModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modelIdArg = args[0] as Long
            val fieldNameArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.getNotesWithFieldsForModel(modelIdArg, fieldNameArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.kanji_scanner.NativeApi.getCardsForModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modelIdArg = args[0] as Long
            val fieldNameArg = args[1] as String
            val offsetArg = args[2] as Long
            val limitArg = args[3] as Long
            val wrapped: List<Any?> = try {
              listOf(api.getCardsForModel(modelIdArg, fieldNameArg, offsetArg, limitArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
