// Autogenerated from Pigeon (v26.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


class GetDecks {
  GetDecks({
    required this.decks,
  });

  Map<int, String> decks;

  List<Object?> _toList() {
    return <Object?>[
      decks,
    ];
  }

  Object encode() {
    return _toList();  }

  static GetDecks decode(Object result) {
    result as List<Object?>;
    return GetDecks(
      decks: (result[0]! as Map<Object?, Object?>).cast<int, String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GetDecks || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(decks, other.decks);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GetModels {
  GetModels({
    required this.models,
  });

  Map<int, String> models;

  List<Object?> _toList() {
    return <Object?>[
      models,
    ];
  }

  Object encode() {
    return _toList();  }

  static GetModels decode(Object result) {
    result as List<Object?>;
    return GetModels(
      models: (result[0]! as Map<Object?, Object?>).cast<int, String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GetModels || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(models, other.models);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class ModelInfo {
  ModelInfo({
    required this.modelId,
    required this.modelName,
    required this.noteCount,
    required this.fields,
  });

  int modelId;

  String modelName;

  int noteCount;

  List<String> fields;

  List<Object?> _toList() {
    return <Object?>[
      modelId,
      modelName,
      noteCount,
      fields,
    ];
  }

  Object encode() {
    return _toList();  }

  static ModelInfo decode(Object result) {
    result as List<Object?>;
    return ModelInfo(
      modelId: result[0]! as int,
      modelName: result[1]! as String,
      noteCount: result[2]! as int,
      fields: (result[3]! as List<Object?>).cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ModelInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(modelId, other.modelId) && _deepEquals(modelName, other.modelName) && _deepEquals(noteCount, other.noteCount) && _deepEquals(fields, other.fields);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GetModelsWithInfo {
  GetModelsWithInfo({
    required this.models,
  });

  List<ModelInfo> models;

  List<Object?> _toList() {
    return <Object?>[
      models,
    ];
  }

  Object encode() {
    return _toList();  }

  static GetModelsWithInfo decode(Object result) {
    result as List<Object?>;
    return GetModelsWithInfo(
      models: (result[0]! as List<Object?>).cast<ModelInfo>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GetModelsWithInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(models, other.models);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GetModelFields {
  GetModelFields({
    required this.fields,
  });

  List<String> fields;

  List<Object?> _toList() {
    return <Object?>[
      fields,
    ];
  }

  Object encode() {
    return _toList();  }

  static GetModelFields decode(Object result) {
    result as List<Object?>;
    return GetModelFields(
      fields: (result[0]! as List<Object?>).cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GetModelFields || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(fields, other.fields);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class NoteWithFields {
  NoteWithFields({
    required this.noteId,
    required this.modelId,
    required this.fields,
    required this.tags,
  });

  int noteId;

  int modelId;

  Map<String, String> fields;

  List<String> tags;

  List<Object?> _toList() {
    return <Object?>[
      noteId,
      modelId,
      fields,
      tags,
    ];
  }

  Object encode() {
    return _toList();  }

  static NoteWithFields decode(Object result) {
    result as List<Object?>;
    return NoteWithFields(
      noteId: result[0]! as int,
      modelId: result[1]! as int,
      fields: (result[2]! as Map<Object?, Object?>).cast<String, String>(),
      tags: (result[3]! as List<Object?>).cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NoteWithFields || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(noteId, other.noteId) && _deepEquals(modelId, other.modelId) && _deepEquals(fields, other.fields) && _deepEquals(tags, other.tags);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GetNotesWithFieldsForModel {
  GetNotesWithFieldsForModel({
    required this.notes,
  });

  List<NoteWithFields> notes;

  List<Object?> _toList() {
    return <Object?>[
      notes,
    ];
  }

  Object encode() {
    return _toList();  }

  static GetNotesWithFieldsForModel decode(Object result) {
    result as List<Object?>;
    return GetNotesWithFieldsForModel(
      notes: (result[0]! as List<Object?>).cast<NoteWithFields>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GetNotesWithFieldsForModel || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(notes, other.notes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class CardInfo {
  CardInfo({
    required this.noteId,
    required this.cardOrd,
    required this.deckId,
    required this.question,
    required this.answer,
    required this.modelId,
    required this.fields,
    required this.tags,
  });

  int noteId;

  int cardOrd;

  int deckId;

  String question;

  String answer;

  int modelId;

  Map<String, String> fields;

  List<String> tags;

  List<Object?> _toList() {
    return <Object?>[
      noteId,
      cardOrd,
      deckId,
      question,
      answer,
      modelId,
      fields,
      tags,
    ];
  }

  Object encode() {
    return _toList();  }

  static CardInfo decode(Object result) {
    result as List<Object?>;
    return CardInfo(
      noteId: result[0]! as int,
      cardOrd: result[1]! as int,
      deckId: result[2]! as int,
      question: result[3]! as String,
      answer: result[4]! as String,
      modelId: result[5]! as int,
      fields: (result[6]! as Map<Object?, Object?>).cast<String, String>(),
      tags: (result[7]! as List<Object?>).cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CardInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(noteId, other.noteId) && _deepEquals(cardOrd, other.cardOrd) && _deepEquals(deckId, other.deckId) && _deepEquals(question, other.question) && _deepEquals(answer, other.answer) && _deepEquals(modelId, other.modelId) && _deepEquals(fields, other.fields) && _deepEquals(tags, other.tags);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GetCardsForModel {
  GetCardsForModel({
    required this.cards,
  });

  List<CardInfo> cards;

  List<Object?> _toList() {
    return <Object?>[
      cards,
    ];
  }

  Object encode() {
    return _toList();  }

  static GetCardsForModel decode(Object result) {
    result as List<Object?>;
    return GetCardsForModel(
      cards: (result[0]! as List<Object?>).cast<CardInfo>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GetCardsForModel || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(cards, other.cards);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is GetDecks) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is GetModels) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is ModelInfo) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is GetModelsWithInfo) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is GetModelFields) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is NoteWithFields) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is GetNotesWithFieldsForModel) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is CardInfo) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is GetCardsForModel) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return GetDecks.decode(readValue(buffer)!);
      case 130:
        return GetModels.decode(readValue(buffer)!);
      case 131:
        return ModelInfo.decode(readValue(buffer)!);
      case 132:
        return GetModelsWithInfo.decode(readValue(buffer)!);
      case 133:
        return GetModelFields.decode(readValue(buffer)!);
      case 134:
        return NoteWithFields.decode(readValue(buffer)!);
      case 135:
        return GetNotesWithFieldsForModel.decode(readValue(buffer)!);
      case 136:
        return CardInfo.decode(readValue(buffer)!);
      case 137:
        return GetCardsForModel.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class NativeApi {
  /// Constructor for [NativeApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NativeApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<GetDecks> getDecks() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.kanji_scanner.NativeApi.getDecks$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as GetDecks;
  }

  Future<GetModels> getModels() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.kanji_scanner.NativeApi.getModels$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as GetModels;
  }

  Future<GetModelsWithInfo> getModelsWithInfo() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.kanji_scanner.NativeApi.getModelsWithInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as GetModelsWithInfo;
  }

  Future<GetModelFields> getModelFields(int modelId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.kanji_scanner.NativeApi.getModelFields$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[modelId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as GetModelFields;
  }

  Future<GetNotesWithFieldsForModel> getNotesWithFieldsForModel(int modelId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.kanji_scanner.NativeApi.getNotesWithFieldsForModel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[modelId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as GetNotesWithFieldsForModel;
  }

  Future<GetCardsForModel> getCardsForModel(int modelId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.kanji_scanner.NativeApi.getCardsForModel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[modelId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as GetCardsForModel;
  }
}
