name: Build Web Extension
description: This action builds the web extension for the project.
inputs:
  web-ext-api-key:
    description: "Web-ext API key"
    required: true
  web-ext-api-secret:
    description: "Web-ext API secret"
    required: true
runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        pnpm add -g nx web-ext
        pnpm install --frozen-lockfile
    - name: Build Extention
      shell: bash
      run: |
        nx run subs2clipboard:build
    - name: Sign Extention
      shell: bash
      run: |
        mkdir -p dist/subs2clipboard
        zip -r dist/subs2clipboard/source.zip apps/subs2clipboard/
        web-ext sign --channel unlisted --api-key ${{ inputs.web-ext-api-key }} --api-secret ${{ inputs.web-ext-api-secret }} --source-dir dist/subs2clipboard --artifacts-dir dist/subs2clipboard --upload-source-code dist/subs2clipboard/source.zip

        VERSION=$(jq -r '.version' apps/subs2clipboard/manifest.json)
        find dist/subs2clipboard -name "*.xpi" -exec mv {} dist/subs2clipboard/Subs2Clipboard-${VERSION}.xpi \;
    - name: Upload Extention Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web-extention
        path: |
          dist/subs2clipboard/*.xpi
        retention-days: 1
