// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_tokenizer`

Future<List<TokenInfo>> sudachiRs({required String text}) =>
    RustLib.instance.api.crateApiSudachiApiSudachiRs(text: text);

void sudachiInitWithDictPath({required String dictPath}) => RustLib.instance.api
    .crateApiSudachiApiSudachiInitWithDictPath(dictPath: dictPath);

class TokenInfo {
  final String surface;
  final String normalized;
  final String reading;
  final String partOfSpeech;

  const TokenInfo({
    required this.surface,
    required this.normalized,
    required this.reading,
    required this.partOfSpeech,
  });

  @override
  int get hashCode =>
      surface.hashCode ^
      normalized.hashCode ^
      reading.hashCode ^
      partOfSpeech.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TokenInfo &&
          runtimeType == other.runtimeType &&
          surface == other.surface &&
          normalized == other.normalized &&
          reading == other.reading &&
          partOfSpeech == other.partOfSpeech;
}
