name: 'publish'
on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  build-cli:
    name: 'Build CLI Tooling'
    strategy:
      fail-fast: false
      matrix:
        arch: [x64, arm64]
        os:
          - name: macos
            image: macos-latest
            shell: bash
            forge_platform: darwin
          - name: linux
            image: ubuntu-22.04
            shell: bash
            forge_platform: linux
          - name: windows
            image: win-signing
            shell: cmd
    runs-on: ${{ matrix.os.image }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Setup node & dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Run the build
        uses: ./.github/actions/build-cli
        with:
          os: ${{ matrix.os.name }}
          # arch: ${{ matrix.arch }}
          shell: ${{ matrix.os.shell }}
    #   - name: Upload the artifact
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: release-desktop-${{ matrix.os.name }}-${{ matrix.arch }}
    #       path: apps/desktop/upload/*.*

  # publish-tauri:
  #   permissions:
  #     contents: write
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       include:
  #         - platform: 'macos-latest' # for Arm based macs (M1 and above).
  #           args: '--target aarch64-apple-darwin'
  #         - platform: 'macos-latest' # for Intel based macs.
  #           args: '--target x86_64-apple-darwin'
  #         - platform: 'ubuntu-22.04'
  #           args: ''
  #         - platform: 'windows-latest'
  #           args: ''

  #   runs-on: ${{ matrix.platform }}
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: install dependencies (ubuntu only)
  #       if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf python3-dev mecab libmecab-dev mecab-ipadic-utf8 git make curl xz-utils file

  #     - name: setup node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: lts/*
  #         cache: 'pnpm' # Set this to npm, yarn or pnpm.

  #     - name: install Rust stable
  #       uses: dtolnay/rust-toolchain@stable # Set this to dtolnay/rust-toolchain@nightly
  #       with:
  #         # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
  #         targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

  #     - name: Rust cache
  #       uses: swatinem/rust-cache@v2
  #       with:
  #         workspaces: './src-tauri -> target'

  #     - name: install frontend dependencies
  #       # If you don't have `beforeBuildCommand` configured you may want to build your frontend here too.
  #       run: pnpm install # change this to npm or pnpm depending on which one you use.

  #     - uses: tauri-apps/tauri-action@v0
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
  #         releaseName: 'App v__VERSION__'
  #         releaseBody: 'See the assets to download this version and install.'
  #         releaseDraft: true
  #         prerelease: false
  #         args: ${{ matrix.args }}